-- ============================================================================
-- TASKFIX_HISTORY.sql — 3: vazifa tarixi (task_history)
-- ============================================================================
-- ADDITIVE + IDEMPOTENT: mavjud jadvallarga TEGMAYDI, faqat yangi jadval
-- qo'shadi. Prod xavfsiz, qayta ishga tushirsa ham buzmaydi.
--
-- NIMA SAQLANADI: faqat 3 ta muhim maydon o'zgarishi —
--   'deadline' | 'assigned_to' (bajaruvchi) | 'status' (holat)
-- Nom/tavsif/prioritet/bo'lim kuzatilmaydi (kelishilgan).
--
-- HAR QATOR: eski→yangi qiymat (xom) + eski→yangi YORLIQ (o'qib bo'ladigan:
-- ism, holat nomi, sana) + kim o'zgartirgani (id VA ism) + qachon.
-- Yorliq saqlanadi, chunki keyinchalik odam o'chirilsa yoki holat nomi
-- o'zgarsa ham tarix o'sha paytdagi holatni ko'rsatishi kerak.
--
-- ⚠️ YOZUVNI MIJOZ QILADI (index.html → thRecord). Ya'ni ilova orqali
--    qilingan o'zgarishlar tushadi; Telegram bot / Edge Function to'g'ridan
--    tasks ni yangilasa — tarixda ko'rinmaydi. To'liq qamrov uchun tasks ga
--    trigger kerak bo'ladi — bu alohida qaror (prod jadvali).
--
-- ⚠️ tasks.id TIPI: repoda tasks sxemasi yo'q (1-37 migratsiyalar yo'q).
--    Shuning uchun task_id ustuni tipi tasks.id dan DINAMIK olinadi —
--    bigint bo'lsa bigint, uuid bo'lsa uuid. Qattiq yozib qo'ymaymiz.
--
-- ESLATMA: TEXT + CHECK (ENUM emas — 30/32-migratsiyalardagi saboq).
-- ============================================================================

BEGIN;

-- ── 0) Oldindan tekshiruv ───────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                  WHERE n.nspname = 'public' AND c.relname = 'tasks') THEN
    RAISE EXCEPTION 'public.tasks topilmadi — noto''g''ri baza?';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE p.proname = 'is_ws_member' AND n.nspname = 'public'
  ) THEN
    RAISE EXCEPTION 'is_ws_member() topilmadi. Avval 39_employee_details.sql ni ishga tushiring.';
  END IF;
END $$;

-- ── 1) Jadval (task_id tipi tasks.id dan olinadi) ───────────────────────────
DO $$
DECLARE
  v_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod) INTO v_type
    FROM pg_attribute a
   WHERE a.attrelid = 'public.tasks'::regclass
     AND a.attname = 'id' AND a.attnum > 0 AND NOT a.attisdropped;

  IF v_type IS NULL THEN
    RAISE EXCEPTION 'public.tasks.id ustuni topilmadi';
  END IF;

  EXECUTE format($f$
    CREATE TABLE IF NOT EXISTS public.task_history (
      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workspace_id    uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
      task_id         %s NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
      field           text NOT NULL,
      old_value       text,
      new_value       text,
      old_label       text,
      new_label       text,
      changed_by      uuid,
      changed_by_name text,
      changed_at      timestamptz NOT NULL DEFAULT now()
    )
  $f$, v_type);

  RAISE NOTICE 'task_history.task_id tipi: % (tasks.id dan olindi)', v_type;
END $$;

-- ── 2) CHECK — faqat kuzatiladigan 3 maydon ─────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'task_history_field_chk'
       AND conrelid = 'public.task_history'::regclass
  ) THEN
    ALTER TABLE public.task_history
      ADD CONSTRAINT task_history_field_chk
      CHECK (field IN ('deadline', 'assigned_to', 'status'));
  END IF;
END $$;

COMMENT ON TABLE  public.task_history IS
  'Vazifaning muhim o''zgarishlari: deadline, bajaruvchi (assigned_to), holat (status). Yozuvni ilova qiladi (index.html → thRecord).';
COMMENT ON COLUMN public.task_history.old_value IS 'Eski xom qiymat (ISO sana / user uuid / status kodi) — matn ko''rinishida';
COMMENT ON COLUMN public.task_history.old_label IS 'Eski qiymatning o''sha paytdagi o''qiladigan yorlig''i (ism / holat nomi / formatlangan sana)';
COMMENT ON COLUMN public.task_history.changed_by_name IS 'O''zgartirgan odam ismi — TEXT, profiles JOIN shart emas (odam o''chsa ham qoladi)';

-- ── 3) Indekslar ────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS task_history_task_idx ON public.task_history (task_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS task_history_ws_idx   ON public.task_history (workspace_id, changed_at DESC);

-- ── 4) RLS ──────────────────────────────────────────────────────────────────
-- KO'RISH: workspace a'zosi (vazifa detalida hamma ko'radi)
-- YOZISH:  workspace a'zosi, lekin faqat O'Z nomidan (changed_by = auth.uid())
-- O'ZGARTIRISH/O'CHIRISH: policy YO'Q → hech kim (tarix o'zgarmas bo'lsin).
--   Vazifa o'chirilsa qatorlar FK CASCADE bilan ketadi — bu normal.
-- ⚠️ workspace_members inline subquery YOZILMAYDI (42P17 rekursiya) — is_ws_member().
ALTER TABLE public.task_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "task_history_select" ON public.task_history;
CREATE POLICY "task_history_select" ON public.task_history FOR SELECT TO authenticated
  USING ( is_ws_member(workspace_id, auth.uid()) );

DROP POLICY IF EXISTS "task_history_insert" ON public.task_history;
CREATE POLICY "task_history_insert" ON public.task_history FOR INSERT TO authenticated
  WITH CHECK ( is_ws_member(workspace_id, auth.uid()) AND changed_by = auth.uid() );

-- ── 5) Tekshiruv — jimgina o'tmasin ─────────────────────────────────────────
DO $$
DECLARE v_cnt int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                  WHERE n.nspname = 'public' AND c.relname = 'task_history') THEN
    RAISE EXCEPTION 'task_history yaratilmadi';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'task_history_field_chk'
                    AND conrelid = 'public.task_history'::regclass) THEN
    RAISE EXCEPTION 'task_history_field_chk qo''shilmadi';
  END IF;

  -- Ustunlar to'liqmi (jadval avval BOSHQA sxema bilan yaratilgan bo'lishi mumkin)
  IF (SELECT count(*) FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'task_history'
         AND column_name IN ('workspace_id','task_id','field','old_value','new_value',
                             'old_label','new_label','changed_by','changed_by_name','changed_at')) <> 10 THEN
    RAISE EXCEPTION 'task_history ustunlari to''liq emas — jadval avval boshqa sxema bilan yaratilgan bo''lishi mumkin. Qo''lda tekshiring.';
  END IF;

  SELECT count(*) INTO v_cnt FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'task_history' AND c.relrowsecurity;
  IF v_cnt = 0 THEN
    RAISE EXCEPTION 'task_history da RLS yoqilmadi';
  END IF;

  SELECT count(*) INTO v_cnt FROM pg_policies
   WHERE schemaname = 'public' AND tablename = 'task_history';
  IF v_cnt < 2 THEN
    RAISE EXCEPTION 'task_history policy''lari to''liq emas (% ta)', v_cnt;
  END IF;

  RAISE NOTICE '✅ task_history tayyor: RLS yoqiq, % ta policy.', v_cnt;
END $$;

COMMIT;

-- ============================================================================
-- ILOVA XATTI-HARAKATI
-- ============================================================================
-- Bu fayl ishga tushmagan bo'lsa — ilova YIQILMAYDI:
--   • vazifa detalida "Tarix" bo'limi "Tarix yoqilmagan..." deb yozadi
--   • saqlash normal ishlaydi, xato faqat console'ga chiqadi (thTableMissing)
-- Ishga tushgandan keyin — hech narsa qilish shart emas, darhol ishlay boshlaydi.
-- ============================================================================
